In [2]:
import numpy as np

In [9]:
mat = np.zeros([8,8])
rhs = np.zeros(8)

In [10]:
for i in np.arange(7):
    mat[i,i]=2.0
    mat[i,i+1]=-1.0
    mat[i+1,i]=-1.0

mat[7,7]=2.0
rhs[7]=0.5
print(mat, rhs)

[[ 2. -1.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0. -1.  2.]] [0.  0.  0.  0.  0.  0.  0.  0.5]


In [11]:
sol = np.linalg.solve(mat, rhs)
print(sol)

[0.05555556 0.11111111 0.16666667 0.22222222 0.27777778 0.33333333
 0.38888889 0.44444444]


In [13]:
import scipy.linalg as la
(P, L, U) = la.lu(mat)
print( P )

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [17]:
print( L )

[[ 1.          0.          0.          0.          0.          0.
   0.          0.        ]
 [-0.5         1.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.         -0.66666667  1.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.         -0.75        1.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.         -0.8         1.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.         -0.83333333  1.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.         -0.85714286
   1.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
  -0.875       1.        ]]
